// File generated by FlutterFire CLI.
// Once Firebase is configured, run:
// flutterfire configure
// to generate this file with your project settings.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_QVonYUQRYLviuZceQa6h7fVJWpMxIY',
    appId: '1:778393830282:android:f41f39393084530cc27e73',
    messagingSenderId: '778393830282',
    projectId: 'traqa-icarus',
    storageBucket: 'traqa-icarus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.traqa.health',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW5VNfD5aGux2EBzpkzogC9k8ekvMlTt4',
    appId: '1:778393830282:web:345f643411a72213c27e73',
    messagingSenderId: '778393830282',
    projectId: 'traqa-icarus',
    authDomain: 'traqa-icarus.firebaseapp.com',
    storageBucket: 'traqa-icarus.firebasestorage.app',
    measurementId: 'G-K90MZ2835H',
  );

}