class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'hi': {
      'appName': 'Traqa',
      'tagline': 'Aapke parivaar ki sehat, seedhi baat mein',
      'chooseLanguage': 'Apni bhasha chuniye',
      'continueBtn': 'Aage badhein',
      'signInGoogle': 'Google se login karo',
      'tabHistory': 'Itihaas',
      'tabFamily': 'Parivaar',
      'tabStreak': 'Sankalp',
      'tabProfile': 'Mera Profile',
      'fabTooltip': 'Report upload karo',
      'uploadTitle': 'Report kaunsi hai?',
      'reportTypeLab': 'Lab Report',
      'reportTypePrescription': 'Doctor ki parchi',
      'reportTypeGeneral': 'Sadharan report',
      'reportTypeMRI': 'MRI Scan',
      'reportTypeXray': 'X-Ray',
      'reportTypeOther': 'Kuch aur',
      'selectOutputLang': 'Jawab kis bhasha mein chahiye?',
      'analyzing': 'Thodi der... samjha raha hoon 🔬',
      'yourReport': 'Aapki report ka matlab',
      'listenBtn': 'Suniye ▶',
      'pauseBtn': 'Rokiye ⏸',
      'addMember': 'Sadasya jodon',
      'familyTitle': 'Mera parivaar',
      'streakTitle': 'Swasthya Sankalp',
      'createStreak': 'Naya sankalp shuru karo',
      'checkIn': 'Aaj ki check-in ✓',
      'shareCard': 'Share karo',
      'profileTitle': 'Mera profile',
      'subscription': 'Subscription',
      'freeFeature': 'FREE — Report samajhna sadaa muft',
      'paidFeatureFamily': 'Parivaar sadasya jodon — ₹50/saal',
      'paidFeatureTracking': 'Sehat tracking — ₹50/maheena',
      'payNow': 'Abhi bharo',
      'healthScore': 'Sehat ka andaaza',
      'improving': 'Sudhar ho raha hai ↑',
      'declining': 'Dhyan chahiye ↓',
      'stable': 'Theek hai →',
      'noReports': 'Abhi tak koi report nahi',
      'uploadFirst': 'Pehli report upload karo',
      'medicationTitle': 'Dawaaiya',
      'whatItTreats': 'Kisliye hai',
      'howToTake': 'Kaise lena hai',
      'sideEffects': 'Asar-andaaz',
      'trendAlert': 'Sehat ki chetavni',
      'doctorAdvice': 'Doctor se baat zaroor karo',
      'disclaimer': 'Yeh sirf jaankari ke liye hai — doctor ki salah zaroor lo',
      'notifPermission': 'Notifications allow karo taaki family ki yaad dilayein',
      'logout': 'Bahar jaao',
      'deleteAccount': 'Account mitao',
      'langChange': 'Bhasha badlo',
      'darkMode': 'Raat ka mode',
      'notifications': 'Suchnaayein',
      'loading': 'Load ho raha hai...',
      'error': 'Kuch gadbad ho gayi',
      'retry': 'Dobara koshish karo',
      'saved': 'Sacha gaya ✓',
      'copied': 'Copy ho gaya',
    },
    // Remaining languages would be added here following the same pattern
    'en': {
      'appName': 'Traqa',
      'tagline': "Your family's health, in words you understand",
      'chooseLanguage': 'Choose your language',
      'continueBtn': 'Continue',
      'signInGoogle': 'Sign in with Google',
      'tabHistory': 'History',
      'tabFamily': 'Family',
      'tabStreak': 'Streak',
      'tabProfile': 'Profile',
      'fabTooltip': 'Upload report',
      'uploadTitle': 'What kind of report?',
      'reportTypeLab': 'Lab Report',
      'reportTypePrescription': "Doctor's Prescription",
      'reportTypeGeneral': 'General Report',
      'reportTypeMRI': 'MRI Scan',
      'reportTypeXray': 'X-Ray',
      'reportTypeOther': 'Other',
      'selectOutputLang': 'Choose explanation language',
      'analyzing': 'Analysing your report... 🔬',
      'yourReport': 'Your Report Explained',
      'listenBtn': 'Listen ▶',
      'pauseBtn': 'Pause ⏸',
      'addMember': 'Add family member',
      'familyTitle': 'My Family',
      'streakTitle': 'Health Streak',
      'createStreak': 'New streak',
      'checkIn': "Today's check-in ✓",
      'shareCard': 'Share',
      'profileTitle': 'My Profile',
      'subscription': 'Subscription',
      'freeFeature': 'FREE — Report decoding always free',
      'paidFeatureFamily': 'Add family member — ₹50/year',
      'paidFeatureTracking': 'Health tracking — ₹50/month',
      'payNow': 'Pay now',
      'healthScore': 'Health Score',
      'improving': 'Improving ↑',
      'declining': 'Needs attention ↓',
      'stable': 'Stable →',
      'noReports': 'No reports yet',
      'uploadFirst': 'Upload your first report',
      'medicationTitle': 'Medications',
      'whatItTreats': 'What it treats',
      'howToTake': 'How to take',
      'sideEffects': 'Side effects',
      'trendAlert': 'Health alert',
      'doctorAdvice': 'Discuss with your doctor',
      'disclaimer': 'This is educational only — always consult your doctor',
      'notifPermission': 'Allow notifications for family health reminders',
      'logout': 'Sign out',
      'deleteAccount': 'Delete account',
      'langChange': 'Change language',
      'darkMode': 'Dark mode',
      'notifications': 'Notifications',
      'loading': 'Loading...',
      'error': 'Something went wrong',
      'retry': 'Retry',
      'saved': 'Saved ✓',
      'copied': 'Copied',
    },
  };

  static String get(String langCode, String key) {
    return translations[langCode]?[key] ?? translations['en']?[key] ?? key;
  }
}